djhydhee

diff --git a/.github/workflows/validate_image_name.yml b/.github/workflows/validate_image_name.yml
--- a/.github/workflows/validate_image_name.yml
+++ b/.github/workflows/validate_image_name.yml
@@ -1,3 +1,4 @@
+---
 name: ECR Image Tag Validation
 
 on:
@@ -40,24 +41,23 @@ jobs:
         id: identify-values-files
         run: |
           #!/bin/bash
+
           # Search for values*.yaml files in the current directory and all subdirectories
           echo "Searching for values*.yaml files..."
           values_files=$(find . -type f -name "values*.yaml")
+
           # Check if any values*.yaml files were found
-          if [ -n "$values_files" ]; then
-              echo "Values*.yaml files found:"
-              echo "$values_files"
-              # Set an output for values files found
-              echo "::set-output name=values_files::$values_files"
-          else
+          if [ -z "$values_files" ]; then
               echo "No values*.yaml files found."
               exit 1
           fi
-          # Initialize variables for overrideTag, image, and latestTag
+          # Initialize variables
           overrideTag=""
-          image=""
           latestTag=""
-          # Extract overrideTag, image, and latestTag fields from values*.yaml files
+          processed_images=()
+          override_found=false  # Flag to indicate if overrideTag is found
+          all_info_found=false  # Flag to indicate if all required information is found
+          # Loop through each values*.yaml file
           for file in $values_files; do
               echo "Processing $file..."
               while IFS= read -r line; do
@@ -65,71 +65,63 @@ jobs:
                   if [[ $line =~ overrideTag:\ (.+) ]]; then
                       overrideTag="${BASH_REMATCH[1]}"
                       echo "OverrideTag: $overrideTag"
-                      #continue
+                      override_found=true  # Set the flag to true
                   fi
                   # Check if image exists
                   if [[ $line =~ image:\ (.+) ]]; then
                       image="${BASH_REMATCH[1]}"
                       echo "Image: $image"
+                      # Pair image with overrideTag
+                      if [[ -n "$overrideTag" ]]; then
+                          echo "Pairing image with overrideTag..."
+                          echo "Image: $image, OverrideTag: $overrideTag"
+                          processed_images+=("$image")
+                      fi
                   fi
-                  # Check if latestTag exists only if overrideTag is not found
-                  if [[ -z "$overrideTag" && $line =~ latestTag:\ (.+) ]]; then
-                      latestTag="${BASH_REMATCH[1]}"
-                      echo "Latest Tag: $latestTag"
+                  # Check if all required information is found
+                  if $override_found && [[ ${#processed_images[@]} -eq number_of_images ]]; then
+                      all_info_found=true
+                      break 2  # Break the outer loop
                   fi
               done < "$file"
-              # Check if overrideTag and image(s) are found, if not, break the loop and look for latestTag
-              if [[ -n "$overrideTag" && -n "$image" ]]; then
-                  break
-              fi
           done
-          # Check if overrideTag and image(s) are found, if not, echo that latestTag will be checked
-          if [[ -z "$overrideTag" && -z "$image" ]]; then
-              echo "OverrideTag and image(s) not found. Checking for latestTag..."
+          # If all required information is found, exit the script
+          if $all_info_found; then
+              echo "All required information found. Exiting."
+              exit 0
           fi
-          # Pair the found tag (overrideTag or latestTag) with all the images
-          if [[ -n "$overrideTag" || -n "$latestTag" ]]; then
-              images=()
+          # If overrideTag is not found, search for latestTag
+          if ! $override_found; then
+              echo "OverrideTag not found. Searching for latestTag..."
+              # Loop through each values*.yaml file
               for file in $values_files; do
                   echo "Processing $file..."
                   while IFS= read -r line; do
+                      # Check if latestTag exists
+                      if [[ $line =~ latestTag:\ (.+) ]]; then
+                          latestTag="${BASH_REMATCH[1]}"
+                          echo "Latest Tag: $latestTag"
+                      fi
                       # Check if image exists
                       if [[ $line =~ image:\ (.+) ]]; then
                           image="${BASH_REMATCH[1]}"
                           echo "Image: $image"
-                          # Pair image with overrideTag or latestTag
-                          if [[ -n "$overrideTag" ]]; then
-                              echo "Pairing image with overrideTag..."
-                              echo "Image: $image, OverrideTag: $overrideTag"
-                          elif [[ -n "$latestTag" ]]; then
+                          # Pair image with latestTag
+                          if [[ -n "$latestTag" ]]; then
                               echo "Pairing image with latestTag..."
                               echo "Image: $image, LatestTag: $latestTag"
                           fi
-                          images+=("$image")
                       fi
                   done < "$file"
               done
-              # Output the images
-              echo "::set-output name=images::${images[*]}"
           fi
+
           # Output the values to be used by the next steps
           echo "::set-output name=overrideTag::$overrideTag"
-          echo "::set-output name=image::$image"
-          # Output latestTag only if overrideTag is not found
-          if [[ -z "$overrideTag" ]]; then
-              echo "::set-output name=latestTag::$latestTag"
-          fi
-      - name: Echo Values
-        run: |
-          echo "overrideTag: $overrideTag"
-          echo "image: $image"
-          echo "latestTag: $latestTag"
-        env:
-          overrideTag: ${{ steps.identify-values-files.outputs.overrideTag }}
-          image: ${{ steps.identify-values-files.outputs.image }}
-          latestTag: ${{ steps.identify-values-files.outputs.latestTag }}
+          echo "::set-output name=latestTag::$latestTag"
 
       - name: List ECR Repositories
+        id: list-ecr-repos
         run: |
           echo "Listing ECR repositories..."
           aws ecr describe-repositories --query 'repositories[*].[repositoryName, repositoryUri]'
@@ -140,7 +132,6 @@ jobs:
         run: |
           # Retrieve values from previous step outputs
           overrideTag=${{ steps.identify-values-files.outputs.overrideTag }}
-          image=${{ steps.identify-values-files.outputs.image }}
           latestTag=${{ steps.identify-values-files.outputs.latestTag }}
           # Retrieve ECR repositories list
           ecr_repositories=$(echo "${{ steps.list-ecr-repos.outputs.ecr_repositories }}" | base64 -d)
@@ -167,7 +158,9 @@ jobs:
           else
               # If neither overrideTag nor latestTag are found, exit with failure
               echo "Error: Neither OverrideTag nor LatestTag provided. Validation failed"
-            fi
+              exit 1
+          fi
+
       - name: Display Validation Result
         run: |
           if [ $? -eq 0 ]; then
