reverse

diff --git a/.github/workflows/validate_image_name.yml b/.github/workflows/validate_image_name.yml
--- a/.github/workflows/validate_image_name.yml
+++ b/.github/workflows/validate_image_name.yml
@@ -34,37 +34,50 @@ jobs:
         id: identify-values-files
         run: |
           #!/bin/bash
-          # Search for values*.yaml files in the current directory and all subdirectories
-          echo "Searching for values*.yaml files..."
-          values_files=$(find . -type f -name "values*.yaml")
-          # Check if any values*.yaml files were found
-          if [ -n "$values_files" ]; then
-              echo "Values*.yaml files found:"
-              echo "$values_files"
-              # Set an output for values files found
-              echo "::set-output name=values_files::$values_files"
+
+          # Search for all YAML files in the current directory and all subdirectories
+          echo "Searching for YAML files..."
+          yaml_files=$(find . -type f -name "*.yaml")
+
+          # Check if any YAML files were found
+          if [ -n "$yaml_files" ]; then
+              echo "YAML files found:"
+              echo "$yaml_files"
+              # Set an output for YAML files found
+              echo "::set-output name=yaml_files::$yaml_files"
           else
-              echo "No values*.yaml files found."
+              echo "No YAML files found."
               exit 1
           fi
+
           # Initialize variables for overrideTag, image, and latestTag
           overrideTag=""
-          image=""
+          images=()
           latestTag=""
-          # Extract overrideTag, image, and latestTag fields from values*.yaml files
-          for file in $values_files; do
+
+          # Extract overrideTag, image, and latestTag fields from YAML files
+          for file in $yaml_files; do
               echo "Processing $file..."
               while IFS= read -r line; do
                   # Check if overrideTag exists
                   if [[ $line =~ overrideTag:\ (.+) ]]; then
                       overrideTag="${BASH_REMATCH[1]}"
                       echo "OverrideTag: $overrideTag"
-                      continue
+                      break 2  # Break both inner and outer loop if overrideTag is found
                   fi
                   # Check if image exists
                   if [[ $line =~ image:\ (.+) ]]; then
                       image="${BASH_REMATCH[1]}"
                       echo "Image: $image"
+                      # Pair image with overrideTag or latestTag
+                      if [[ -n "$overrideTag" ]]; then
+                          echo "Pairing image with overrideTag..."
+                          echo "Image: $image, OverrideTag: $overrideTag"
+                      elif [[ -n "$latestTag" ]]; then
+                          echo "Pairing image with latestTag..."
+                          echo "Image: $image, LatestTag: $latestTag"
+                      fi
+                      images+=("$image")
                   fi
                   # Check if latestTag exists only if overrideTag is not found
                   if [[ -z "$overrideTag" && $line =~ latestTag:\ (.+) ]]; then
@@ -72,60 +85,57 @@ jobs:
                       echo "Latest Tag: $latestTag"
                   fi
               done < "$file"
-              # Check if overrideTag and image(s) are found, if not, break the loop and look for latestTag
-              if [[ -n "$overrideTag" && -n "$image" ]]; then
-                  break
-              fi
           done
-          # Check if overrideTag and image(s) are found, if not, echo that latestTag will be checked
-          if [[ -z "$overrideTag" && -z "$image" ]]; then
-              echo "OverrideTag and image(s) not found. Checking for latestTag..."
-          fi
+
           # Output the values to be used by the next steps
           echo "::set-output name=overrideTag::$overrideTag"
-          echo "::set-output name=image::$image"
-          # Output latestTag only if overrideTag is not found
-          if [[ -z "$overrideTag" ]]; then
-              echo "::set-output name=latestTag::$latestTag"
-          fi
+          echo "::set-output name=latestTag::$latestTag"
+          echo "::set-output name=images::${images[*]}"
 
       - name: List ECR Repositories
+        id: list-ecr-repos
         run: |
           echo "Listing ECR repositories..."
           aws ecr describe-repositories --query 'repositories[*].[repositoryName, repositoryUri]'  
-          echo "::set-output name=ecr_repositories::$(aws ecr describe-repositories --query 'repositories[*].[repositoryName, repositoryUri]' --output table)"
+          echo "::set-output name=ecr_repositories::$(aws ecr describe-repositories --query 'repositories[*].[repositoryName, repositoryUri]' --output json)"
 
       - name: Check Overrides and Validate Image Tags in ECR
-        if: ${{ steps.identify-values-files.outputs.values_files != '' }}
+        if: ${{ steps.identify-values-files.outputs.yaml_files != '' }}
         run: |
           # Retrieve values from previous step outputs
           overrideTag=${{ steps.identify-values-files.outputs.overrideTag }}
-          image=${{ steps.identify-values-files.outputs.image }}
+          images=(${{ steps.identify-values-files.outputs.images }})
           latestTag=${{ steps.identify-values-files.outputs.latestTag }}
           # Retrieve ECR repositories list
-          ecr_repositories=$(echo "${{ steps.list-ecr-repos.outputs.ecr_repositories }}" | base64 -d)
+          ecr_repositories=$(echo "${{ steps.list-ecr-repos.outputs.ecr_repositories }}" | jq -r '.[] | select(contains(["'$overrideTag'", "'$latestTag'"])).[1]')
           # Check if overrideTag exists in ECR repositories
           if [[ -n "$overrideTag" ]]; then
               echo "Checking overrideTag against ECR repositories..."
-              if echo "$ecr_repositories" | grep -q "$overrideTag"; then
+              if [[ -n "$ecr_repositories" ]]; then
                   echo "OverrideTag '$overrideTag' found in ECR. Validation successful."
-                  echo "Pairing image with overrideTag..."
-                  echo "Image: $image, OverrideTag: $overrideTag"
-                  exit 0
+                  for image in "${images[@]}"; do
+                      echo "Pairing image with overrideTag..."
+                      echo "Image: $image, OverrideTag: $overrideTag"
+                  done
               else
                   echo "Error: OverrideTag '$overrideTag' not found in ECR repository. Validation failed."
+                  exit 1
               fi
           fi
           # Check if latestTag exists in ECR repositories
-          if echo "$ecr_repositories" | grep -q "$latestTag"; then
-              echo "LatestTag '$latestTag' found in ECR. Validation successful."
-              echo "Pairing image with latestTag..."
-              echo "Image: $image, LatestTag: $latestTag"
-          else
-              echo "Error: LatestTag '$latestTag' not found in ECR repository. Validation failed."
-              exit 1
+          if [[ -n "$latestTag" ]]; then
+              echo "Checking latestTag against ECR repositories..."
+              if [[ -n "$ecr_repositories" ]]; then
+                  for image in "${images[@]}"; do
+                      echo "Pairing image with latestTag..."
+                      echo "Image: $image, LatestTag: $latestTag"
+                  done
+              else
+                  echo "Error: LatestTag '$latestTag' not found in ECR repository. Validation failed."
+                  exit 1
+              fi
           fi
-          
+
       - name: Display Validation Result
         run: |
           if [ $? -eq 0 ]; then
