djdjkdj

diff --git a/.github/workflows/validate_image_name.yml b/.github/workflows/validate_image_name.yml
--- a/.github/workflows/validate_image_name.yml
+++ b/.github/workflows/validate_image_name.yml
@@ -1,4 +1,3 @@
----
 name: ECR Image Tag Validation
 on:
   pull_request:
@@ -44,10 +43,12 @@ jobs:
               echo "No values*.yaml files found."
               exit 1
           fi
+
           # Initialize variables for overrideTag, image, and latestTag
           overrideTag=""
-          image=""
+          images=()
           latestTag=""
+
           # Extract overrideTag, image, and latestTag fields from values*.yaml files
           for file in $values_files; do
               echo "Processing $file..."
@@ -60,31 +61,31 @@ jobs:
                   fi
                   # Check if image exists
                   if [[ $line =~ image:\ (.+) ]]; then
-                      image="${BASH_REMATCH[1]}"
-                      echo "Image: $image"
+                      # Capture all image values and append them to the array
+                      images+=("${BASH_REMATCH[1]}")
                   fi
-                  # Check if latestTag exists only if overrideTag is not found
+                  # Check if latestTag exists
                   if [[ -z "$overrideTag" && $line =~ latestTag:\ (.+) ]]; then
                       latestTag="${BASH_REMATCH[1]}"
                       echo "Latest Tag: $latestTag"
                   fi
               done < "$file"
-              # Check if overrideTag and image(s) are found, if not, break the loop and look for latestTag
-              if [[ -n "$overrideTag" && -n "$image" ]]; then
+              # Check if overrideTag is not found and image(s) are found
+              if [[ -z "$overrideTag" && ${#images[@]} -gt 0 ]]; then
                   break
               fi
           done
-          # Check if overrideTag and image(s) are found, if not, echo that latestTag will be checked
-          if [[ -z "$overrideTag" && -z "$image" ]]; then
-              echo "OverrideTag and image(s) not found. Checking for latestTag..."
+
+          # Check if overrideTag is not found and image(s) are found, if not, echo that latestTag will be checked
+          if [[ -z "$overrideTag" && ${#images[@]} -eq 0 ]]; then
+              echo "OverrideTag not found. Checking for image(s) and latestTag..."
           fi
+
           # Output the values to be used by the next steps
           echo "::set-output name=overrideTag::$overrideTag"
-          echo "::set-output name=image::$image"
-          # Output latestTag only if overrideTag is not found
-          if [[ -z "$overrideTag" ]]; then
-              echo "::set-output name=latestTag::$latestTag"
-          fi
+          echo "::set-output name=images::${images[*]}"
+          echo "::set-output name=latestTag::$latestTag"
+
 
       - name: List ECR Repositories
         run: |
@@ -132,11 +133,7 @@ jobs:
               echo "Error: Neither OverrideTag nor LatestTag found. Validation failed."
               exit 1
           fi
-          
+
       - name: Display Validation Result
         run: |
-          if [ $? -eq 0 ]; then
-              echo "Validation successful. All image tags are valid."
-          else
-              echo  "Validation failed. There are issues with the image tags."
-          fi
+          if [ $? -eq
