djdne

diff --git a/.github/workflows/validate_image_name.yml b/.github/workflows/validate_image_name.yml
--- a/.github/workflows/validate_image_name.yml
+++ b/.github/workflows/validate_image_name.yml
@@ -162,39 +162,40 @@ jobs:
           echo "$ecr_repositories" 
         
       - name: Describe ECR Images
-        run: |
-          # Get the output from the List ECR Repos step
-          ecr_repositories_output=$(aws ecr describe-repositories --query 'repositories[*].[repositoryName, repositoryUri]' --output json)
+       run: |
+    # Get the output from the List ECR Repos step
+    ecr_repositories_output=$(aws ecr describe-repositories --query 'repositories[*].[repositoryName, repositoryUri]' --output json)
 
-          # Check if the JSON output is not null
-          if [ -n "$ecr_repositories_output" ]; then
-            # Ensure that the ecr_repositories_output is properly formatted JSON
-            echo "$ecr_repositories_output" | jq -e . >/dev/null || { echo "Invalid JSON output from List ECR Repos step"; exit 1; }
+    # Check if the JSON output is not null
+    if [ -n "$ecr_repositories_output" ]; then
+      # Ensure that the ecr_repositories_output is properly formatted JSON
+      echo "$ecr_repositories_output" | jq -e . >/dev/null || { echo "Invalid JSON output from List ECR Repos step"; exit 1; }
 
-            # Iterate through each repository
-            echo "$ecr_repositories_output" | jq -r '.[] | @tsv' | while IFS=$'\t' read -r repo_name repo_uri; do
-              echo "Repo Name: $repo_name, Repo URI: $repo_uri"
-              if [ -n "$repo_uri" ]; then
-                # Extract registry ID and region from repository URI
-                registry_id=$(echo "$repo_uri" | cut -d'.' -f1)
-                region=$(echo "$repo_uri" | cut -d'.' -f4)
-                if [ -n "$registry_id" ] && [ -n "$region" ]; then
-                  echo "Describing images for repository: $repo_name ($repo_uri)"
-                  echo "Extracted Registry ID: $registry_id"
-                  echo "Extracted Region: $region"
-                  # Describe images using AWS CLI
-                  images_output=$(aws ecr describe-images --registry-id "$registry_id" --repository-name "$repo_name" --image-ids "$latestTag")
-                  echo "$images_output" | jq -r '.imageDetails[] | "Registry ID: \(.registryId), Repository Name: \(.repositoryName), Image Tag: \(.imageTags[0])"' >> "$GITHUB_OUTPUT"
-                else
-                  echo "Unable to extract Registry ID and Region for repository: $repo_name ($repo_uri)"
-                fi
-              else
-                echo "Skipping empty repository URI."
-              fi
-            done
+      # Iterate through each repository
+      echo "$ecr_repositories_output" | jq -r '.[] | @tsv' | while IFS=$'\t' read -r repo_name repo_uri; do
+        echo "Repo Name: $repo_name, Repo URI: $repo_uri"
+        if [ -n "$repo_uri" ]; then
+          # Extract registry ID and region from repository URI
+          registry_id=$(echo "$repo_uri" | cut -d'.' -f1)
+          region=$(echo "$repo_uri" | cut -d'.' -f4)
+          if [ -n "$registry_id" ] && [ -n "$region" ]; then
+            echo "Describing images for repository: $repo_name ($repo_uri)"
+            echo "Extracted Registry ID: $registry_id"
+            echo "Extracted Region: $region"
+            # Describe images using AWS CLI
+            images_output=$(aws ecr describe-images --registry-id "$registry_id" --repository-name "$repo_name" --image-ids "$latestTag")
+            echo "$images_output" | jq -r '.imageDetails[] | "Registry ID: \(.registryId), Repository Name: \(.repositoryName), Image Tag: \(.imageTags[0])"' >> "$GITHUB_OUTPUT"
           else
-            echo "No output received from List ECR Repos step. Skipping Describe ECR Images step."
+            echo "Unable to extract Registry ID and Region for repository: $repo_name ($repo_uri)"
           fi
+        else
+          echo "Skipping empty repository URI."
+        fi
+      done
+    else
+      echo "No output received from List ECR Repos step. Skipping Describe ECR Images step."
+    fi
+
 
       - name: Process ECR Image Details
         if: steps.describe-ecr-images.outputs.images != 'null'
